### PR TITLE
Bug/id 27/the user cannot create a new product

### PR DESCRIPTION
**Pull request by Karvlox**
What have I done?
The logic implemented to correctly upload the products to the DB has been modified.

How have I done this?
By modifying the module which manages and works communicating with the DB.

Why have I done this?
So that products can be uploaded to the DB

Author: @Karvlox
Reviewer: @Elvis-Castro-H 
Proof: @Misax148 

Link | Click Up | Bug : https://app.clickup.com/t/8686h13jg
QA - TEST: Victor Alejandro Cespedes Cartagena - AntWood

### CODE REVIEW

**Review by Elvis-Castro-H — APPROVED** [review]
No comments

**Comment by Misax148** [comment]
Is working correctly, but, when this US will ready for QA y will receive bugs, because this admin panel don't have validations, so you need to add.

image

So when I create a new product without data, just redirected me to the admin panel view, is neccesary add validations.
image

**Comment by Misax148** [comment]
Before to add a product, or realize the creation, you need validate that the inputs are filled or is neccesary the missing camps.

image

**Review by Misax148 — APPROVED** [review]
Good job!

**Pull request merged**
